project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Scott Forrest"

  navbar:
    left:
      - text: Home
        href: index.qmd
      # - about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching and Workshops"
        href: teaching.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Blog"
        href: blog.qmd
      - text: CV
        href: cv.qmd

    right: 
      - icon: github
        href: https://github.com/swforrest/
      - icon: envelope-at-fill
        href: mailto:scottwforrest@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/swforrest/

  sidebar:
      - title: "Research"
        style: floating
        contents: 
          - research.qmd
          - research/*
      - title: "Teaching and Workshops"
        contents: 
          - teaching.qmd
          - teaching/*
      - title: "Blog"
        contents: 
          - blog.qmd
          - posts/*

format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true

