project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Scott Forrest"
  google-analytics: 
    tracking-id: "G-0P938DSNYB"
    storage: none

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      # - about.qmd
      - text: "Research"
        href: research.qmd
      # - text: "Teaching and Workshops"
      #   href: teaching.qmd
      # - text: "Talks"
      #   href: talks.qmd
      # - text: "Blog"
      #   href: blog.qmd
      - text: "CV"
        href: cv.qmd

    right: 
      - text: "deepSSF"
        href: https://swforrest.github.io/deepSSF/
      - icon: github
        href: https://github.com/swforrest/
      - icon: envelope-at-fill
        href: mailto:scottwforrest@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/swforrest/

  sidebar:
      - title: "Research"
        style: floating
        contents: 
          - research.qmd
          - auto: "research/*"
      - title: "Teaching and Workshops"
        contents: 
          - teaching.qmd
          - auto: "teaching/*"
      - title: "Blog"
        contents: 
          - blog.qmd
          - auto: "posts/*"

  page-footer:
    background: light
    center:
      - icon: envelope-at-fill
        href: mailto:scottwforrest@gmail.com
      - icon: github
        href: https://github.com/swforrest
      - icon: linkedin
        href: https://www.linkedin.com/in/swforrest/
      - text: "Scholar"
        href: https://scholar.google.com.au/citations?user=ECYMO3YAAAAJ&hl=en&authuser=1

format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true



